import type {Metadata} from "next";
import {Rubik} from "next/font/google";
import "./globals.css";
import "modern-normalize/modern-normalize.css";
import React from "react";
import styles from "./Layout.module.css";
import {Footer} from "@/app/components/Footer";
import {Navbar} from "@/app/components/Navbar";

const inter = Rubik({subsets: ["latin", "cyrillic"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar/>
        <main className={styles.mainContent}>
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    );
}
